load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "public-macro",
    srcs = glob(['src/**/*.rs']),
    edition = "2021",
    deps = [
                "@my_crates_macro_demo//:quote",
                "@my_crates_macro_demo//:syn",

    ],
    visibility = ["//visibility:public"],

)
