[project]
name = "my_project"
version = "0.1.0"
dependencies = [
    "requests>=2.28.0",
    "numpy==1.26.4",
    "pandas==2.2.3",
]

[build-system]
requires = [
    "setuptools==70.0.0",  # Pinned version
    "wheel==0.43.0",       # Pinned version
]
build-backend = "setuptools.build_meta"