load("//hello_world:rule.bzl", "generate_file")

generate_file(
    name = "r1",
    output_file = "start1.txt",
    text = "hello,world!",
)

generate_file(
    name = "r2",
    output_file = "start2.txt",
    text = "China",
)
