load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "my-macro",
    srcs = glob(['src/**/*.rs']),
    edition = "2021",
    deps = [
        "@my_crates//:syn-2.0.106",
        "@my_crates//:quote",
        "@my_crates//:venial",
        "@my_crates//:proc-macro-error",
        "@my_crates//:proc-macro2",
    ],
    visibility = ["//rust_demo:__subpackages__"],

)
