load("@llvm-project//mlir:tblgen.bzl", "gentbl_cc_library", "td_library")

td_library(
    name = "td_files",
    srcs = [
        "include/PengDialect.td",
    ],
    deps = [
        "@llvm-project//mlir:BuiltinDialectTdFiles",
        "@llvm-project//mlir:InferIntRangeInterfaceTdFiles",
        "@llvm-project//mlir:InferTypeOpInterfaceTdFiles",
        "@llvm-project//mlir:OpBaseTdFiles",
        "@llvm-project//mlir:SideEffectInterfacesTdFiles",
    ],
)

gentbl_cc_library(
    name = "dialect_inc_gen",
    tbl_outs = [
        (
            ["-gen-dialect-decls"],
            "PengDialect.h.inc",
        ),
        (
            ["-gen-dialect-defs"],
            "PengDialect.cpp.inc",
        ),
    ],
    tblgen = "@llvm-project//mlir:mlir-tblgen",
    td_file = "include/PengDialect.td",
    deps = [
        ":td_files",
    ],
)

cc_library(
    name = "peng_dialect_lib",
    srcs = [
        "PengDialect.cpp",
    ],
    hdrs = [
        "include/PengDialect.h",
    ],
    deps = [
        ":dialect_inc_gen",
        "@llvm-project//mlir:ComplexDialect",
        "@llvm-project//mlir:Dialect",
        "@llvm-project//mlir:IR",
        "@llvm-project//mlir:InferIntRangeInterface",
        "@llvm-project//mlir:InferTypeOpInterface",
        "@llvm-project//mlir:Support",
    ],
)


cc_binary(
    name = "main",
    srcs = ["main.cpp"],
    deps = [
        ":peng_dialect_lib",

    ],
)