load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")
#load("@rules_rust_pyo3//:defs.bzl", "pyo3_extension", "pyo3_toolchain")

rust_library(
    name = "rustlib",
    srcs = glob(["**/*.rs"]),
    crate_features = [
        "extension-module",
        "abi3-py313",
    ],
    #    crate_type = "staticlib",
    crate_name = "rustlib",
    edition = "2021",
    proc_macro_deps = [
        "//rust_demo/my-macro:my-macro",  # ✅ 这里正确使用 proc_macro_deps
    ],
    rustc_flags = [
        "--crate-type=staticlib",
    ],
    visibility = ["//rust_demo:__subpackages__"],
    deps = [
        "//rust_demo/cpp:cpp_core",
        "@my_crates//:cxx",
        "@my_crates//:pyo3",
        "@my_crates//:rand",
        "@my_crates//:serde",
        "@my_crates//:syn",
        "@my_crates//:tempfile",
        "@my_crates//:tokio",
    ],
)

#rust_library(
#    name = "rustlib2",
#    srcs = glob(["**/*.rs"]),
#    #    crate_type = "staticlib",
#    crate_name = "rustlib2",
#    edition = "2021",
#    rustc_flags = [
#        "--crate-type=staticlib",
#    ],
#    crate_features = ["extension-module", "abi3-py313"],
#
#    visibility = ["//rust_demo:__subpackages__"],
#    deps = [
#        "@my_crates//:rand",
#        "@my_crates//:serde",
#        "@my_crates//:tempfile",
#        "@my_crates//:cxx",
#        "@my_crates//:pyo3",
#
#    ],
#)

# ---------- Rust → Python 扩展 ----------
#pyo3_extension(
#    name = "rust_lib_ext",               # 生成的 .so / .pyd 文件名
#    srcs = glob(["**/*.rs"]),
#    crate_root = "lib.rs",
#    # 可选：额外依赖
#    # deps = [":some_rust_dep"],
#    visibility = ["//visibility:public"],
#    deps = [
#        ":rustlib",
#
#   ]
#)
#
#rust_library(
#    name = "rust_demo2",
#    srcs = glob(["**/*.rs"]),
#    edition = "2021",
#    deps = [
#        ":rust_lib_ext",
#    ],
#)

rust_test(
    name = "rust_demo_test",
    args = ["--nocapture"],
    crate = ":rustlib",
    #    srcs = glob(["**/*.rs"]),
    edition = "2021",
    deps = [
        "@my_crates//:trybuild",
    ],
)
