load("@nanobind_bazel//:build_defs.bzl", "nanobind_extension")

#cc_library(
#    name = "_basic_lib",
#    srcs = [
#        "lib/MyCoroutine.cpp",
#        "lib/MyCoroutine.h",
#        "lib/THPVariableMeta.cpp",
#        "lib/THPVariableMeta.h",
#        "lib/demo_type.cc",
#        "lib/demo_type.h",
#    ],
#    copts = select({
#        "@platforms//os:windows": ["/std:c++20"],  # MSVC
#        "@platforms//os:linux": ["-std=c++20"],  # GCC/Clang
#        "//conditions:default": [],
#    }),
#    deps = [
#
#    ],
#)

nanobind_extension(
    name = "basic",
    srcs = [
        "nanobind_python.cpp",
    ],
    copts = select({
        "@platforms//os:windows": ["/std:c++20"],  # MSVC
        "@platforms//os:linux": ["-std=c++20"],  # GCC/Clang
        "//conditions:default": [],
    }),
    data = ["basic.pyi"],
    deps = [
        "//rust_demo/cpp_lib",
        "@fmt",
    ],
)

py_library(
    name = "basic_lib",
    srcs = [
        "tools.py",
    ],
    data = [
        ":basic",
    ],
    imports = ["."],
)

py_test(
    name = "python_basic_test",
    srcs = ["python_basic_test.py"],
    deps = [
        ":basic_lib",
    ],
)
#py_library(
#    name = "basic_lib2",
#    srcs = [
#        "tools.py"
#    ],
#    data = [
#        ":basic",
#        "//rust_demo/rustlib:rust_demo2",
#
#    ],
#    imports = ["."],
#)

#py_test(
#    name = "python_basic_test2",
#    srcs = ["python_basic_test2.py"],
#    data = [
#     ],
#    deps = [
#        ':basic_lib2'
#    ],
#)
