load("@rules_rust//rust:defs.bzl", "rust_proc_macro")

rust_proc_macro(
    name = "other-macro",
    srcs = glob(['src/**/*.rs']),
    edition = "2021",
    deps = [
                "@my_crates_macro//:quote",
                "@my_crates_macro//:syn",

    ],
    visibility = ["//visibility:public"],

)
